services:
  postgres:
    image: postgres:16
    container_name: flightops-postgres
    environment:
      POSTGRES_DB: flightops
      POSTGRES_USER: flightops
      POSTGRES_PASSWORD: flightops
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U flightops -d flightops"]
       interval: 5s
       timeout: 3s
       retries: 20

volumes:
  pgdata: